### ISSUE TITLE
[web] モリサワフォントを使いたい

### ISSUE THREAD

**Issue by wf-yamaday** [and-period/furumaru#33]
## 概要

- フリーライセンスになったらしいのでWeb側のフォントでモリサワフォントを使いたい。  
https://github.com/googlefonts/morisawa-biz-ud-gothic/
- Google Fontsでの例  
https://fonts.google.com/?query=Morisawa+Inc.&preview.text=%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%81%AE%E5%95%86%E5%93%81&preview.text_type=custom

**Comment by taba2424** [comment]
世界のモリサワね、いいね!🤔

**Comment by hamachans** [comment]
世界のヨコサワみたいにいうな
